"""Sync user fields

Revision ID: 2789adec4ca8
Revises: 2718c326eccc
Create Date: 2026-08-02 16:16:38.222599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2789adec4ca8'
down_revision: Union[str, Sequence[str], None] = '2718c326eccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('contact_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('passing_out_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('current_course', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_course')
    op.drop_column('users', 'domain')
    op.drop_column('users', 'passing_out_year')
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
