"""add plain_password to users

Revision ID: b307fb4b62dc
Revises: 2789adec4ca8
Create Date: 2026-08-02 18:02:34.017047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b307fb4b62dc'
down_revision: Union[str, Sequence[str], None] = '2789adec4ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plain_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plain_password')
    # ### end Alembic commands ###
